# File: docs/environment.yaml

name: docs
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - pysam==0.16.0.1
  - biopython==1.79
  - pandas==1.2.4
  - numpy==1.20.3
  - matplotlib==3.4.2
